USE MERCADONA_DB;
DROP FUNCTION IF EXISTS INCREASE_CARR_CANT;
DELIMITER //
CREATE FUNCTION INCREASE_CARR_CANT(
    CARRITO BIGINT,
    OBJETO VARCHAR(60)
)
RETURNS INT
DETERMINISTIC
BEGIN
    SET @ACTUAL = (
        SELECT CARR_CANT 
        FROM CARRITO_COMPRAS_DETALLE
        WHERE ID_CARRITO = CARRITO AND ID_OBJETO = OBJETO
    );

    RETURN @ACTUAL + 1;

END //
DELIMITER ;

USE MERCADONA_DB;
DROP FUNCTION IF EXISTS COTIZAR;
DELIMITER //
CREATE FUNCTION COTIZAR(
    CANTIDAD INT,
    OBJETO BIGINT
)
RETURNS FLOAT
DETERMINISTIC
BEGIN

    SET @PORCENTAJE = (SELECT RAND()*(10-5)+5); #PORCENTAJE ENTRE EL 5 Y 10
    SET @PORCENTAJE = (@PORCENTAJE*0.10);
    SET @PORCENTAJE = ROUND(@PORCENTAJE, 1);

    SET @PRECIO = (SELECT OBJ_PRECIO FROM OBJETOS WHERE ID_OBJ = OBJETO);
    SET @DESCUENTO = (@PRECIO * @PORCENTAJE);
    SET @RESULTADO = (@PRECIO - @DESCUENTO)*CANTIDAD;

    RETURN @RESULTADO;

END //
DELIMITER ;

USE MERCADONA_DB;
DROP FUNCTION IF EXISTS INVENTARIO;
DELIMITER //
CREATE FUNCTION INVENTARIO( OBJ BIGINT, CANTIDAD INT)
RETURNS INT
DETERMINISTIC
BEGIN

    SET @INVENTARIO = (SELECT OBJ_CANT FROM OBJETOS WHERE ID_OBJ = OBJ);

    SET @VALID = IF(CANTIDAD > @INVENTARIO, 0, 1);
    RETURN @VALID;

END //
DELIMITER ;