USE MERCADONA_DB;
DROP FUNCTION IF EXISTS INCREASE_CARR_CANT;
DELIMITER //
CREATE FUNCTION INCREASE_CARR_CANT(
    CARRITO BIGINT,
    OBJETO VARCHAR(60)
)
RETURNS INT
DETERMINISTIC
BEGIN
    SET @ACTUAL = (
        SELECT CARR_CANT 
        FROM CARRITO_COMPRAS_DETALLE
        WHERE ID_CARRITO = CARRITO AND ID_OBJETO = OBJETO
    );

    RETURN @ACTUAL + 1;

END //
DELIMITER ;

USE MERCADONA_DB;
DROP FUNCTION IF EXISTS COTIZAR;
DELIMITER //
CREATE FUNCTION COTIZAR(
    CANTIDAD TINYINT,
    OBJETO BIGINT
)
RETURNS FLOAT
DETERMINISTIC
BEGIN

    SET @DESCUENTO = (SELECT RAND()*(10-5)+5); #PORCENTAJE ENTRE EL 5 Y 10
    SET @DESCUENTO = (@DESCUENTO*0.10);
    SET @DESCUENTO = ROUND(@DESCUENTO, 1);

    SET @PRECIO = (SELECT OBJ_PRECIO FROM OBJETOS WHERE ID_OBJ = OBJETO);
    SET @PRECIO = (@PRECIO * @DESCUENTO)*CANTIDAD;

    RETURN @PRECIO;

END //
DELIMITER ;