USE MERCADONA_DB;
DROP FUNCTION IF EXISTS INCREASE_CARR_CANT;
DELIMITER //
CREATE FUNCTION INCREASE_CARR_CANT(
    CARRITO BIGINT,
    OBJETO VARCHAR(60)
)
RETURNS INT
DETERMINISTIC
BEGIN
    SET @ACTUAL = (
        SELECT CARR_CANT 
        FROM CARRITO_COMPRAS_DETALLE
        WHERE ID_CARRITO = CARRITO AND ID_OBJETO = OBJETO
    );

    RETURN @ACTUAL + 1;

END //
DELIMITER ;