USE MERCADONA_DB;
DROP TRIGGER IF EXISTS TR_INSERTAR_OBJ;
DELIMITER //
CREATE TRIGGER TR_INSERTAR_OBJ
AFTER INSERT
ON OBJETOS FOR EACH ROW
BEGIN

    SET @CATEGORIA = (SELECT CATEGORIA FROM HOLDER LIMIT 1);

    INSERT INTO CATEGORIA_OBJETO(
        ID_CAT,
        ID_OBJ,
        ALTA
    ) VALUES (@CATEGORIA, NEW.ID_OBJ, SYSDATE());

    #ALTER TABLE OBJETOS DROP COLUMN TMP_CATEGORIA;
END //
DELIMITER ;

USE MERCADONA_DB;
DROP TRIGGER IF EXISTS TR_ELIMINAR_LISTA;
DELIMITER //
CREATE TRIGGER TR_ELIMINAR_LISTA
BEFORE DELETE
ON D_LISTAS FOR EACH ROW
BEGIN

    DELETE FROM D_LISTAS_DETALLE 
        WHERE ID_LISTA = OLD.ID_LISTA;

END //
DELIMITER ;

USE MERCADONA_DB;
DROP TRIGGER IF EXISTS TR_NUEVO_USUARIO;
DELIMITER //
CREATE TRIGGER TR_NUEVO_USUARIO
AFTER INSERT 
ON USUARIOS FOR EACH ROW
BEGIN

    INSERT INTO CARRITO_COMPRAS(CARR_USR, CARR_ALTA)
        VALUES(NEW.USR_CORREO, SYSDATE());

END //
DELIMITER ;

USE MERCADONA_DB;
DROP TRIGGER IF EXISTS TR_ADD_TO_CART;
DELIMITER //
CREATE TRIGGER TR_ADD_TO_CART
BEFORE INSERT
ON CARRITO_COMPRAS_DETALLE FOR EACH ROW
BEGIN

    SET @CANTIDAD = (SELECT OBJ_CANT FROM OBJETOS WHERE ID_OBJ = NEW.ID_OBJETO);

    IF( @CANTIDAD > 0) THEN
        UPDATE OBJETOS SET OBJ_CANT = (@CANTIDAD - 1) WHERE ID_OBJ = NEW.ID_OBJETO; 
    ELSE
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'No hay suficientes';
    END IF;

END //
DELIMITER ;