USE MERCADONA_DB;
DROP VIEW IF EXISTS VW_PORTADA_OBJETO;
CREATE VIEW VW_PORTADA_OBJETO AS
    SELECT DISTINCT
        M.MEDIA_REC AS 'PORTADA',
        O.OBJ_NMBRE AS 'TITULO',
        O.OBJ_DESC AS 'DESCRIPCION',
        IF(O.OBJ_COT = b'1', 'Cotizar', O.OBJ_PRECIO) AS 'PRECIO',
        O.ID_OBJ AS 'OBJETO',
        O.OBJ_VEND AS 'VENDEDOR'
    FROM OBJETOS AS O
    JOIN MULTIMEDIA AS M
    ON M.ID_OBJ = O.ID_OBJ;